/*
                  Kubermatic Enterprise Read-Only License
                         Version 1.0 ("KERO-1.0”)
                     Copyright © 2025 Kubermatic GmbH

   1.	You may only view, read and display for studying purposes the source
      code of the software licensed under this license, and, to the extent
      explicitly provided under this license, the binary code.
   2.	Any use of the software which exceeds the foregoing right, including,
      without limitation, its execution, compilation, copying, modification
      and distribution, is expressly prohibited.
   3.	THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
      EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
      MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
      IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
      CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
      TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
      SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

   END OF TERMS AND CONDITIONS
*/

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TunnelSpec defines the desired state of Tunnel
type TunnelSpec struct {
	// Hostname is the hostname of the tunnel. If not specified, the hostname will be generated by KubeLB.
	// +optional
	Hostname string `json:"hostname,omitempty"`
}

// TunnelStatus defines the observed state of Tunnel
type TunnelStatus struct {
	// Hostname contains the actual hostname assigned to the tunnel
	// +optional
	Hostname string `json:"hostname,omitempty"`

	// URL contains the full URL to access the tunnel
	// +optional
	URL string `json:"url,omitempty"`

	// ConnectionManagerURL contains the URL that clients should use to establish tunnel connections
	// +optional
	ConnectionManagerURL string `json:"connectionManagerURL,omitempty"`

	// Phase represents the current phase of the tunnel
	// +optional
	Phase TunnelPhase `json:"phase,omitempty"`

	// Resources contains references to the resources created for this tunnel
	// +optional
	Resources TunnelResources `json:"resources,omitempty"`

	// Conditions represents the current conditions of the tunnel
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// TunnelResources contains references to resources created for the tunnel
type TunnelResources struct {
	// ServiceName is the name of the service created for this tunnel
	// +optional
	ServiceName string `json:"serviceName,omitempty"`

	// RouteRef is a reference to the route (HTTPRoute or Ingress) created for this tunnel
	// +optional
	RouteRef *corev1.ObjectReference `json:"routeRef,omitempty"`
}

// TunnelPhase represents the phase of tunnel
type TunnelPhase string

const (
	// TunnelPhasePending means the tunnel is being provisioned
	TunnelPhasePending TunnelPhase = "Pending"
	// TunnelPhaseReady means the tunnel is ready to accept connections
	TunnelPhaseReady TunnelPhase = "Ready"
	// TunnelPhaseFailed means the tunnel provisioning failed
	TunnelPhaseFailed TunnelPhase = "Failed"
	// TunnelPhaseTerminating means the tunnel is being terminated
	TunnelPhaseTerminating TunnelPhase = "Terminating"
)

// +kubebuilder:resource:scope=Namespaced
// +kubebuilder:object:generate=true
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:JSONPath=".status.hostname",name="Hostname",type="string"
// +kubebuilder:printcolumn:JSONPath=".status.phase",name="Phase",type="string"
// +kubebuilder:printcolumn:JSONPath=".metadata.creationTimestamp",name="Age",type="date"

// Tunnel is the Schema for the tunnels API
type Tunnel struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   TunnelSpec   `json:"spec,omitempty"`
	Status TunnelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TunnelList contains a list of Tunnel
type TunnelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Tunnel `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Tunnel{}, &TunnelList{})
}
