/*
                  Kubermatic Enterprise Read-Only License
                         Version 1.0 ("KERO-1.0")
                     Copyright © 2026 Kubermatic GmbH

   1.	You may only view, read and display for studying purposes the source
      code of the software licensed under this license, and, to the extent
      explicitly provided under this license, the binary code.
   2.	Any use of the software which exceeds the foregoing right, including,
      without limitation, its execution, compilation, copying, modification
      and distribution, is expressly prohibited.
   3.	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
      EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
      MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
      IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
      CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
      TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
      SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

   END OF TERMS AND CONDITIONS
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// WAFFailureMode defines how routes behave when WAF filter creation fails.
// +kubebuilder:validation:Enum=Open;Closed
type WAFFailureMode string

const (
	// WAFFailureModeOpen allows traffic through without WAF protection if filter fails.
	WAFFailureModeOpen WAFFailureMode = "Open"

	// WAFFailureModeClosed blocks traffic if WAF filter cannot be applied.
	WAFFailureModeClosed WAFFailureMode = "Closed"
)

// WAFTargetRef identifies a route by name.
type WAFTargetRef struct {
	// Group is the API group of the target resource.
	// +kubebuilder:default="gateway.networking.k8s.io"
	Group string `json:"group,omitempty"`

	// Kind is the kind of the target resource.
	// +kubebuilder:validation:Enum=HTTPRoute;GRPCRoute
	Kind string `json:"kind"`

	// Namespace is the management cluster namespace (e.g., tenant-primary).
	// If omitted, matches across all namespaces.
	// +optional
	Namespace string `json:"namespace,omitempty"`

	// Name is the name of the target resource which could either be the name of the resource in management cluster
	// that is generated by KubeLB or the `kubelb.k8c.io/origin-name` that is the original name of the resource in the tenant cluster.
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`
}

// WAFPolicySpec defines the desired state of WAFPolicy.
// Exactly one targeting method must be used: targetRef, targetSelector, or neither (global default).
// Setting both targetRef and targetSelector is invalid.
// Feature stage: Alpha
// +kubebuilder:validation:XValidation:rule="!(has(self.targetRef) && has(self.targetSelector))",message="targetRef and targetSelector are mutually exclusive"
type WAFPolicySpec struct {
	// TargetRef identifies a specific route by name and optionally namespace.
	// Mutually exclusive with TargetSelector.
	// +optional
	TargetRef *WAFTargetRef `json:"targetRef,omitempty"`

	// TargetSelector selects routes or HTTPRoute/GRPCRoute resources by label.
	// It checks whether the route has the labels or the labels of the HTTPRoute/GRPCRoute resource. In case of a
	// conflict, the labels of the Route resource takes precedence.
	// Mutually exclusive with TargetRef.
	// +optional
	TargetSelector *metav1.LabelSelector `json:"targetSelector,omitempty"`

	// Directives contains SecLang/ModSecurity directives passed to Coraza.
	// Reference: https://coraza.io/docs/seclang/directives/
	//
	// If empty, the following OWASP CRS defaults are applied:
	//   - SecRuleEngine On
	//   - SecRequestBodyAccess On
	//   - SecRequestBodyLimit 13107200
	//   - Include @crs-setup-conf
	//   - Include @owasp_crs/*.conf
	//
	// +optional
	Directives []string `json:"directives,omitempty"`

	// FailureMode defines behavior when WAF filter creation fails.
	// - Closed: Block traffic if WAF cannot be applied (default)
	// - Open: Allow traffic without WAF protection
	// +kubebuilder:default=Closed
	// +optional
	FailureMode WAFFailureMode `json:"failureMode,omitempty"`
}

// WAFPolicyStatus defines the observed state of WAFPolicy.
type WAFPolicyStatus struct {
	// Conditions describe the current state of the WAFPolicy.
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster
// +kubebuilder:printcolumn:JSONPath=".spec.targetRef.name",name="Target",type="string"
// +kubebuilder:printcolumn:JSONPath=".status.conditions[?(@.type==\"Valid\")].status",name="Valid",type="string"

// WAFPolicy defines Web Application Firewall policy for L7 routes.
// Applies to HTTPRoute, GRPCRoute, and Ingress resources.
type WAFPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   WAFPolicySpec   `json:"spec,omitempty"`
	Status WAFPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WAFPolicyList contains a list of WAFPolicy.
type WAFPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WAFPolicy `json:"items"`
}

func init() {
	SchemeBuilder.Register(&WAFPolicy{}, &WAFPolicyList{})
}
