/*
Copyright 2026 The KubeLB Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package main implements a documentation generator for KubeLB Prometheus metrics.
// It reads metric definitions from the metrics packages and generates markdown documentation.
//
// Usage:
//
//	go run ./internal/metricsutil/metricsdocs > docs/metrics.md
package main

import (
	"bytes"
	"fmt"
	"os"
	"sort"
	"strings"
	"text/template"

	"k8c.io/kubelb/internal/metricsutil"
	"k8c.io/kubelb/internal/metricsutil/ccm"
	"k8c.io/kubelb/internal/metricsutil/envoycp"
	"k8c.io/kubelb/internal/metricsutil/manager"
)

const docTemplate = `# KubeLB Metrics Reference

This document describes all Prometheus metrics exposed by KubeLB components.

> **Note:** This documentation is auto-generated. Run ` + "`make generate-metricsdocs`" + ` to regenerate.
> Do not edit this file manually.

## Table of Contents

- [Manager Metrics](#manager-metrics)
- [CCM Metrics](#ccm-metrics)
- [EnvoyCP Metrics](#envoycp-metrics)

---

## Manager Metrics

Metrics exposed by the KubeLB Manager component (kubelb-manager).

| Metric | Type | Description | Labels |
|--------|------|-------------|--------|
{{- range .Manager}}
| ` + "`{{.Name}}`" + ` | {{.Type}} | {{.Help}} | {{formatLabels .Labels}} |
{{- end}}

---

## CCM Metrics

Metrics exposed by the KubeLB Cloud Controller Manager component (kubelb-ccm).

| Metric | Type | Description | Labels |
|--------|------|-------------|--------|
{{- range .CCM}}
| ` + "`{{.Name}}`" + ` | {{.Type}} | {{.Help}} | {{formatLabels .Labels}} |
{{- end}}

---

## EnvoyCP Metrics

Metrics exposed by the KubeLB Envoy Control Plane component.

| Metric | Type | Description | Labels |
|--------|------|-------------|--------|
{{- range .EnvoyCP}}
| ` + "`{{.Name}}`" + ` | {{.Type}} | {{.Help}} | {{formatLabels .Labels}} |
{{- end}}

---

## Label Reference

Common labels used across KubeLB metrics:

| Label | Description |
|-------|-------------|
| ` + "`namespace`" + ` | Kubernetes namespace of the resource |
| ` + "`tenant`" + ` | KubeLB tenant identifier |
| ` + "`result`" + ` | Reconciliation result: ` + "`success`" + `, ` + "`error`" + `, or ` + "`skipped`" + ` |
| ` + "`route_type`" + ` | Type of route: ` + "`ingress`" + `, ` + "`gateway`" + `, ` + "`httproute`" + `, ` + "`grpcroute`" + ` |
| ` + "`topology`" + ` | Envoy proxy topology: ` + "`shared`" + `, ` + "`dedicated`" + `, ` + "`global`" + ` |
| ` + "`operation`" + ` | Operation type for KubeLB cluster operations |
| ` + "`snapshot_name`" + ` | Envoy xDS snapshot identifier |
| ` + "`type_url`" + ` | Envoy xDS resource type URL |
`

type templateData struct {
	Manager []metricsutil.MetricDescription
	CCM     []metricsutil.MetricDescription
	EnvoyCP []metricsutil.MetricDescription
}

func main() {
	// Collect all metrics
	data := templateData{
		Manager: manager.ListMetrics(),
		CCM:     ccm.ListMetrics(),
		EnvoyCP: envoycp.ListMetrics(),
	}

	// Sort metrics alphabetically by name within each component
	sort.Slice(data.Manager, func(i, j int) bool {
		return data.Manager[i].Name < data.Manager[j].Name
	})
	sort.Slice(data.CCM, func(i, j int) bool {
		return data.CCM[i].Name < data.CCM[j].Name
	})
	sort.Slice(data.EnvoyCP, func(i, j int) bool {
		return data.EnvoyCP[i].Name < data.EnvoyCP[j].Name
	})

	// Create template with helper functions
	funcMap := template.FuncMap{
		"formatLabels": formatLabels,
	}

	tmpl, err := template.New("metrics").Funcs(funcMap).Parse(docTemplate)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing template: %v\n", err)
		os.Exit(1)
	}

	// Execute template
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		fmt.Fprintf(os.Stderr, "Error executing template: %v\n", err)
		os.Exit(1)
	}

	// Output to stdout
	fmt.Print(buf.String())
}

// formatLabels formats a slice of label names for display in a markdown table.
func formatLabels(labels []string) string {
	if len(labels) == 0 {
		return "-"
	}
	// Format each label with backticks
	formatted := make([]string, len(labels))
	for i, l := range labels {
		formatted[i] = "`" + l + "`"
	}
	return strings.Join(formatted, ", ")
}
