replicaCount: 1

image:
  repository: quay.io/kubermatic/kubelb-ccm
  pullPolicy: IfNotPresent
  tag: v1.0.0
imagePullSecrets: []

kubelb:
  ## -- Name of the tenant, must be unique against a load balancer cluster.
  tenantName: null
  enableLeaderElection: true
  nodeAddressType: InternalIP
  ## -- Name of the secret that contains kubeconfig for the loadbalancer cluster
  clusterSecretName: kubelb-cluster
  # -- useIngressClass specifies whether to target resources with `kubelb` ingress class or all resources.
  useIngressClass: true
  # -- useGatewayClass specifies whether to target resources with `kubelb` gateway class or all resources.
  useGatewayClass: true
  # -- useLoadBalancerClass specifies whether to target services of type LoadBalancer with `kubelb` load balancer class or all services of type LoadBalancer.
  useLoadBalancerClass: false
  # -- disableGatewayAPI specifies whether to disable the Gateway API and Gateway Controllers.
  disableGatewayAPI: false
  # -- disableIngressController specifies whether to disable the Ingress Controller.
  disableIngressController: false
  # -- disableGatewayController specifies whether to disable the Gateway Controller.
  disableGatewayController: false
  ## -- disableHTTPRouteController specifies whether to disable the HTTPRoute Controller.
  disableHTTPRouteController: false
  ## -- disableGRPCRouteController specifies whether to disable the GRPCRoute Controller.
  disableGRPCRouteController: false

extraVolumes: []
extraVolumeMounts: []

nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}

## RBAC
serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  enabled: true
  allowProxyRole: true
  allowMetricsReaderRole: true
  allowLeaderElectionRole: true

# Monitoring Configuration
serviceMonitor:
  enabled: false

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsUser: 65532

service:
  type: ClusterIP
  port: 8443
  protocol: TCP

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
