{{- if .Values.kubelb.tunnel.enabled }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubelb-manager.fullname" . }}-connection-manager
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kubelb-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: tunnel-connection-manager
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}