resources:
- ../base
namespace: tenant-secondary
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/args/-"
      value: "--cluster-name=tenant-secondary"
  target:
    kind: Deployment
