apiVersion: v2
name: kubelb-addons
description: Helm chart for KubeLB Addons
icon: https://raw.githubusercontent.com/kubermatic/kubelb/main/docs/kubelb-logo.png
type: application
maintainers:
  - name: Kubermatic
    email: support@kubermatic.com
    url: https://kubermatic.com
version: v0.3.2
appVersion: v0.3.2
dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
    version: 4.15.1
  - name: gateway-helm
    repository: oci://docker.io/envoyproxy
    condition: envoy-gateway.enabled
    version: 1.7.1
    alias: envoy-gateway
  - name: cert-manager
    repository: oci://quay.io/jetstack/charts
    condition: cert-manager.enabled
    version: v1.20.2
  - name: external-dns
    repository: https://kubernetes-sigs.github.io/external-dns
    condition: external-dns.enabled
    version: 1.20.0
  - name: metallb
    repository: oci://quay.io/metallb/chart
    condition: metallb.enabled
    version: 0.15.3
  - name: agentgateway-crds
    repository: oci://cr.agentgateway.dev/charts
    condition: agentgateway-crds.enabled
    version: v1.1.0
  - name: agentgateway
    repository: oci://cr.agentgateway.dev/charts
    condition: agentgateway.enabled
    version: v1.1.0
